pipeline {

    agent any

    parameters {

        choice(
            name: 'ACTION',
            choices: ['plan', 'apply', 'destroy'],
            description: 'Terraform Action'
        )

        choice(
            name: 'ENV',
            choices: ['prod'],
            description: 'Environment'
        )
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform-modules-project-full') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform-modules-project-full') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Action') {

            steps {

                dir('terraform-modules-project-full') {

                    script {

                        if(params.ACTION=="plan"){

                            sh "terraform plan -var-file=${params.ENV}.tfvars"

                        }

                        if(params.ACTION=="apply"){

                            sh "terraform apply -auto-approve -var-file=${params.ENV}.tfvars"

                        }

                        if(params.ACTION=="destroy"){

                            sh "terraform destroy -auto-approve -var-file=${params.ENV}.tfvars"

                        }

                    }

                }

            }

        }

    }

}
